# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002ee31e03127871e4239b8f1da484a260ccdf04c2ddd697a8e270a6aef4fb591a69a11863c537b0f5e23fe52ad273cebea5ec4d977c368bf51559a1e7a18105

test:
  secret_key_base: 54eb4bb0b1d96a9b40650cdab442c790d8e9555814a086d623ab92a14548ce4e6b8b76e90e721a41afebcab2374061c65cd9384333813748f686c6157fe3a842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
